### getServerInfos
GET http://192.168.110.206:20880/license/getServerInfos?osName=linux

###
GET http://127.0.0.1:8080/license/getServerInfos?osName=windows

### generateLicense
#POST http://192.168.110.206:20880/license/generateLicense
POST  http://127.0.0.1:8080/license/generateLicense
Content-Type: application/json

{
  "subject":"license_cxyj",
  "privateAlias":"privateKey",
  "keyPass":"cxyj123456",
  "storePass":"cxyj123456",
  "licensePath":"/data/cxkj/fireRescueServer/license/license.lic",
  "privateKeysStorePath":"/data/cxkj/fireRescueServer/license/privateKeys.keystore",
  "issuedTime":"2020-10-10 00:00:01",
  "expiryTime":"2030-10-09 23:59:59",
  "consumerType":"User",
  "consumerAmount":1,
  "description":"license for cxyj",
  "licenseCheckModel":{
    "ipAddress": [
    ],
    "macAddress": [
    ],
    "cpuSerial": "",
    "mainBoardSerial": ""
  }
}

### verify
GET http://localhost:8080/license/verify

### verify
GET http://192.168.110.206:20880/license/verify
